### ISSUE TITLE
How to integrate with sonar

### ISSUE THREAD

**Issue by vramasam** [gmazzo/gradle-android-test-aggregation-plugin#64]
Hello @gmazzo 

We have noticed final reports is having all the html files. But for sonar will expect executable file as input. 

In general if we have the feasibility of integrate the final output from the plugin to sonar. Can you please mention the steps in the readme if it available. Thank you in Advance.

Example : <sonar.jacoco.reportPath>${project.basedir}/../target/jacoco.exec</sonar.jacoco.reportPath>

**Comment by gmazzo** [comment]
Like #63, configuring Sonar is out of scope of this plugin. This plugin is meant to fill the gap between [AGP](https://developer.android.com/build) and [JaCoCo Report Aggregation Plugin](https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html)

Again, said that, instead of referring the `.exec` files (wich are single execution data generated by JaCoCo instrumentation on each Test task) you should be providing the aggregated report outcome, in XML format:
```kotlin
plugins {
    id("org.sonarqube") version "4.3.1.3277"
}

sonar {
    properties {
        property("sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml")
    }
}

tasks.sonar {
    dependsOn(tasks.jacocoAggregatedReport)
}
```

Sadly, the `sonar` plugin is poorly designed and you can't use [Property API](https://docs.gradle.org/current/userguide/lazy_configuration.html) on it to have it linked property in a Gradle way :(
