### ISSUE TITLE
Unit tests with Hilt are not taken into account by Jacoco

### ISSUE THREAD

**Issue by agherschon** [gmazzo/gradle-android-test-aggregation-plugin#92]
Hello,

Apparently having Hilt annotated unit tests are not imported into Jacoco as it doesn't know about the generated classes of Hilt/Dagger.

Here's the ticket on Google's tracker: https://issuetracker.google.com/issues/161300933#comment5

There's a workaround by apparently adding the generated path of those classes that should be around `\build\intermediates\classes\normalDebug\transformNormalDebugClassesWithAsm\dirs\`, so the question is, what is the DSL I can use of this plugin to add this? Or even better, could this plugin import those in case they exist automatically? 

Thanks in advance 🙏🏻

**Comment by gmazzo** [comment]
Hi @agherschon!

Unfurtuonally, as you stated already, I don't think this is an issue from this plugin but rather from the `artifacts.fromScope` API that is not including all the generated classes with ASM:
```kotlin
artifacts
    .forScope(ScopedArtifacts.Scope.PROJECT)
    .use(allVariantsClassesForCoverageReport)
    .toGet(ScopedArtifact.CLASSES, { allVariantsJars }, { allVariantsDirs })
```

> what is the DSL I can use of this plugin to add this?

There is a helper `Sync` `allVariantsClassesForCoverageReport` task registered on EACH Android module that is used to collect (and expose) `.class` files from all.

You may manually add `build\intermediates\classes\normalDebug\transformNormalDebugClassesWithAsm` to that to try to workaround the issue. I'd recommend you to target the task that generates the folder instead, which I think is with per-variant, with the format `transform<VariantName>ClassesWithAsm`.

In your case, I think it will be:
```kotlin
tasks.allVariantsClassesForCoverageReport {
    from(tasks.named("transformNormalDebugClassesWithAsm"))
}
```

> could this plugin import those in case they exist automatically?

Like with other issues (like with `androidTest` code coverage), I'd like to avoid as much as possible accessing internals of AGP because of the risk of breaking.
